//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1RM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C1RM()
        {
            this.C1RMWorkout = new HashSet<C1RMWorkout>();
        }
    
        public int RMID { get; set; }
        public string UserID { get; set; }
        public float UserWeight { get; set; }
        public System.DateTime RMDate { get; set; }
    
        public virtual EWPUser EWPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C1RMWorkout> C1RMWorkout { get; set; }
    }
}
