//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelativeStrengthT
    {
        public int RelativeStrengthID { get; set; }
        public int WorkoutID { get; set; }
        public float RelativeStrengthValue { get; set; }
        public int RelativeStrengthPoint { get; set; }
        public string Sex { get; set; }
    
        public virtual Workout Workout { get; set; }
    }
}
