//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutMuscle
    {
        public int WorkoutMuscleID { get; set; }
        public int WorkoutID { get; set; }
        public int MuscleID { get; set; }
        public bool PrimMover { get; set; }
        public bool Synergist { get; set; }
        public bool Stabilizer { get; set; }
        public bool Lengthening { get; set; }
    
        public virtual Muscle Muscle { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
